### ISSUE TITLE
What is the goal or result of this RNN language model ?

### ISSUE THREAD

**Issue by guotong1988** [pangolulu/rnn-from-scratch#1]
Thank you .

**Comment by gy910210** [comment]
You can generate text by this RNN language model, more fantastic examples can be found in http://karpathy.github.io/2015/05/21/rnn-effectiveness/.

**Comment by guotong1988** [comment]
多谢大神，问下应该训练多少epoch？我训练了10个epoch之后只能生成一些the，a，I之类的词

**Comment by gy910210** [comment]
第一，这里的训练集还是太小；第二，只用CPU训练太慢了，10个epoch不一定能收敛；第三，纯RNN对long term的记忆不好，现在主流都是用LSTM等。

PS. 我的代码只是toy，为了理解RNN的机制。

我写了一个用Google Tensorflow训练语言模型的代码，可以参考https://github.com/pangolulu/char-rnnlm-tensorflow

希望对你有帮助。
