### ISSUE TITLE
大神，您好，弱问下这个RNN训练好之后能做什么?

### ISSUE THREAD

**Issue by guotong1988** [pangolulu/rnn-from-scratch#2]
不太明白这个RNN在做什么，X是句子，Y是句子，

X_train shape: (78483,)
y_train shape: (78483,)
x:
SENTENCE_START what are n't you understanding about this ? !
[0, 51, 27, 16, 10, 857, 53, 25, 34, 69]
y:
what are n't you understanding about this ? ! SENTENCE_END
[51, 27, 16, 10, 857, 53, 25, 34, 69, 1]

**Comment by lanpay-lulu** [comment]
这个就是做的一个语言模型，相当于每次输入句子中的一个词，预测下一个词
